#!/bin/sh
#chkconfig: 123456 90 10
daemon_start() {
    python /mnt/webdata/Blog/webserver/server.py &
    echo "Server started."
}
daemon_stop() {
    pid=`ps -ef | grep '[p]ython /mnt/webdata/Blog/webserver/server.py' | awk '{ print $2 }'`
    echo $pid
    kill $pid
    sleep 2
    echo "Server killed."
}

case "$1" in
    start)
        daemon_start
        ;;
    stop)
        daemon_stop
        ;;
    restart)
        daemon_stop
        daemon_start
        ;;
    *)
        echo "Usage: /home/ftpuser/io_mq_service/publisher {start|stop|restart}"
        exit 1
esac
exit 0

